version: '4'
services:
  chat-server-main:
    extends:
      file: ./chatserver_express/docker-compose.yaml
      service: chat-server

  mongo:
    extends:
      file: ./chatserver_express/docker-compose.yaml
      service: mongo

networks:
  chat-server-networks:
    driver: bridge