version: '4'

networks:
  main-be:
    driver: bridge
  chat-server-networks:
    driver: bridge

services:

  # MAIN BACKEND
  main-be-server:
    extends:
      file: ./backend_flask/docker-compose.yml
      service: app
  
  mysql:
    extends:
      file: ./backend_flask/docker-compose.yml
      service: mysql

  redis:
    extends:
      file: ./backend_flask/docker-compose.yml
      service: redis

  # CHAT SERVER
  chat-server-main:
    extends:
      file: ./chatserver_express/docker-compose.yaml
      service: chat-server

  mongo:
    extends:
      file: ./chatserver_express/docker-compose.yaml
      service: mongo