version: '3'
services:
  chat-server:
    build: ./server
    depends_on:
      - mongo
    volumes:
      - ./chat-server-logs:/usr/src/app/logs
    ports:
      - 30002:${CHAT_SERVER_PORT}
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/${MONGO_INITDB_DATABASE}
      MONGO_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      PORT: ${CHAT_SERVER_PORT}
      TZ: Asia/Ho_Chi_Minh
    networks:
      - chat-server-networks
    command: yarn start

  mongo:
    image: mongo:7.0-rc-jammy
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      TZ: Asia/Ho_Chi_Minh
    networks:
      - chat-server-networks

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN : 'true'
  #     TZ: Asia/Ho_Chi_Minh
  #   networks:
  #     - chat-server-networks

networks:
 chat-server-networks:
    driver: bridge