version: '4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mysql
      - redis
    environment:
      DBUSERNAME: ${DBUSERNAME}
      DBPASSWORD: ${DBPASSWORD}
      DBNAME: ${DBNAME}
    ports:
      - 10000:10000
    networks:
      - main-be
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 3309:3306
    networks:
      - main-be
    environment:
      MYSQL_DATABASE: ${DBUSERNAME}
      MYSQL_USER: ${DBUSERNAME}
      MYSQL_ROOT_PASSWORD: ${DBPASSWORD}

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - main-be
    command: 'redis-server --save 60 1 --loglevel warning --requirepass ${REDISPASSWORD}'

networks:
  main-be:
    driver: bridge